{% set name = "olctools" %}
{% set version = "1.0.6" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "bb693268fc0bf368affb31a2609d55d62d5d4ada452852f211bbefdb55f07ff4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/O/OLCTools/OLCTools-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python >=3
  run:
    - python >=3
    - pytest

test:
  imports:
    - accessoryFunctions
    - biotools
    - coreGenome
    - databasesetup
    - metagenomefilter
    - sipprCommon
    - spadespipeline

about:
  home: https://github.com/lowandrew/OLCTools
  license: UNKNOWN
  license_family: OTHER
  license_file: ''
  summary: Summary of the package
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
