language: python
python:
  - '3.6'
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install python=3.6.8
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda config --add channels olcbioinformatics
  - conda install -c olcbioinformatics olctools=1.2.0=py_0

script:
  - python -m pytest -s -vv --maxfail=1
