language: python
python:
  - '3.5'
cache: pip

install:
  - pip install -r requirements.txt
  - wget https://sourceforge.net/projects/bbmap/files/BBMap_37.76.tar.gz
  - tar xf BBMap_37.76.tar.gz
  - export PATH=$PATH:$PWD/bbmap/
  - wget https://github.com/refresh-bio/KMC/releases/download/v3.1.0/KMC3.1.0.linux.tar.gz && tar xf KMC3.1.0.linux.tar.gz
  - export PATH=$PATH:$PWD
  - wget https://github.com/marbl/Mash/releases/download/v2.0/mash-Linux64-v2.0.tar && tar xf mash-Linux64-v2.0.tar && export PATH=$PATH:$PWD/mash-Linux64-v2.0
  - pip install -e .
branches:
  only:
    - master

script:
  - python -m pytest
