site_name: OLCTools

theme: readthedocs
repo_url: "https://github.com/lowandrew/OLCTools"

pages:
    - Home: index.md
    - BioTools:
        - bbtools.md
        - jellyfish.md
        - kmc.md
        - mash.md
