site_name: OLCTools

theme: readthedocs
repo_url: "https://github.com/lowandrew/OLCTools"

pages:
    - Home: index.md
    - AccessoryFunctions: AccessoryFunctions.md
    - BioTools:
        - BBTools.md
        - Jellyfish.md
        - KMC.md
        - Mash.md
